
version: '3.4'

services:
  announcensboards:
    container_name: server
    image: ${DOCKER_REGISTRY-}announcensboard
    depends_on:
      - database
      - redis
    environment:
        WAIT_HOSTS: database:5432, redis:6379
    build:
      context: .
      dockerfile: AnnouncensBoard/Dockerfile
    
      
      
  
  database:
    container_name: postgres
    hostname: postgres
    image: postgres   
    restart: always
    environment:
        POSTGRES_DB: announcens_db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
       - "6379:6379"
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

  client:
    image: vue-client
    container_name: vue-client
    build: ../Extra/vue-client
    ports:
       - "8080:8080"
    volumes:
       - /vue-client:/var/www/html/app

  proxy:
    image: proxy
    container_name: proxy
    build: ../Extra/Nginx
    ports:
        - 443:443
    depends_on:
       - client
       - announcensboards
    restart: always
  
    