
version: '3.4'

services:
  announcensboard:
    image: ${DOCKER_REGISTRY-}announcensboard
    depends_on:
      - database
      - redis
    environment:
        WAIT_HOSTS: database:5432, redis:6379
    build:
      context: .
      dockerfile: AnnouncensBoard/Dockerfile
    networks:
       - asp-network
      
      
  
  database:
    container_name: postgres
    image: postgres   
    restart: always
    environment:
        POSTGRES_DB: my_db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgres/data
    networks:
       - asp-network

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
       - "6379:6379"
    volumes:
      - /path/to/local/data:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    networks:
      - asp-network

networks:
    asp-network:
       driver: bridge
volumes:
  postgres-data:
    