<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <UserSecretsId>d3db7af4-ee7c-4dc9-8176-02743f4ca1c9</UserSecretsId>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.Extensions.SecretManager.Tools" Version="2.0.0"/>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="8.0.7" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AnnoucensBoard.Domain\AnnoucensBoard.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Repository\TopicStore.cs" />
    <Compile Remove="Repository\**" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="Repository\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Repository\**" />
  </ItemGroup>

</Project>
